default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('PG_USERNAME') %>
  password: <%= ENV.fetch('PG_PASSWORD')  %>
  host: localhost

development:
  <<: *default
  database: moviesapp_development

test:
  <<: *default
  database: moviesapp_test

production:
  <<: *default
  database: moviesapp_production
  username: moviesapp
  password: <%= ENV["MOVIESAPP_DATABASE_PASSWORD"] %>
